ERROR [2018-05-25 16:25:19,186] (app.py:1560): Exception on /v1/role/edit [POST]
Traceback (most recent call last):
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\CloudSync\bak\virtualenv\python3flask\lib\site-packages\flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "H:/workspace/UlordOpenApi\ulord\apiv1\__init__.py", line 96, in decorator
    return f(*args, **kwargs)
  File "H:/workspace/UlordOpenApi\ulord\apiv1\__init__.py", line 86, in decorator
    return f(*args, **kwargs)
  File "H:/workspace/UlordOpenApi\ulord\forms\__init__.py", line 26, in inner
    return f(*args,**kwargs)
  File "H:/workspace/UlordOpenApi\ulord\apiv1\role.py", line 45, in role_edit
    des = f.form.des.data
NameError: name 'f' is not defined
